SiteCaDir/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views import defaults
from django.urls import re_path
from django.views.static import serve

def custom_page_not_found(request):
    return defaults.page_not_found(request, None)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('core.urls', namespace='core')),
    path('programas/', include('programas.urls', namespace='programas')),
    path('ouvidoria/', include('ouvidoria.urls', namespace='ouvidoria')),
    path('eventos/', include('eventos.urls', namespace='eventos')),
    path('guias/', include('guias.urls', namespace='guias')),
    path('institucional/', include('institucional.urls', namespace='institucional')),

    # Debbuging url
    path('404/', custom_page_not_found),
]

urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

core/urls.py
from django.urls import path, include
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.main_page, name='main'),
]

guias/urls.py
from django.urls import path, include
from guias import views

app_name = 'guias'

urlpatterns = [
    # Index Path
    path('', views.index, name='guias_index'),
    # Show Path
    path('<int:pk>', views.show, name='guias_show'),
    path('assistencia_estudantil', views.assistencia_estudantil, name='assistencia_estudantil'),
    path('aluno_estrangeiro', views.estrangeiro, name='aluno_estrangeiro'),
    path('fluxo', views.fluxo, name='fluxo'),
    path('manual_do_calouro', views.calouro, name='manual_do_calouro'),
    path('matricula_web', views.matricula_web, name='matricula_web'),
    path('monitoria', views.monitoria, name='monitoria'),
    path('pcne', views.pcne, name='pcne'),
    path('predios_unb', views.predios, name='predios_unb'),
    path('transferencia', views.tranferencia, name='transferencia'),
    path('transporte', views.transporte, name='transporte')
]

guias/models.py
from django.db import models


# Create your models here.
class Guia(models.Model):
    # Nome do guia
    nome = models.CharField('Nome', max_length=60)
    # Descrição do guia
    desc = models.TextField('Descrição', default='Guia CADir UnB')
    # Duração da leitura
    duracao = models.IntegerField('Duração de leitura', default=30, help_text='Colocar a duração em minutos')
    # Link para guia externo
    link = models.URLField('Link', blank=True)
    # File para dowload
    file = models.FileField('Arquivo', upload_to='guias_pdf', blank=True)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name_plural = "Guias"
        verbose_name = "Guia"

guias/views.py
from django.shortcuts import render
from .models import Guia


# Create your views here.

def index(request):
    template_name = 'guias_index_dinamico.html'
    context = {
        "Guias": Guia.objects.order_by("nome")
    }
    return render(request, template_name, context)


def show(request, **kwargs):
    template_name = 'guia_show.html'
    context = {
        "Guia": Guia.objects.filter(id=int(kwargs['pk'])).get()
    }
    return render(request, template_name, context)


def assistencia_estudantil(request):
    template_name = 'assistencia_estudantil.html'
    context = {}
    return render(request, template_name, context)


def estrangeiro(request):
    template_name = 'estrangeiro.html'
    context = {}
    return render(request, template_name, context)


def fluxo(request):
    template_name = 'fluxo.html'
    context = {}
    return render(request, template_name, context)


def calouro(request):
    template_name = 'manual_do_calouro.html'
    context = {}
    return render(request, template_name, context)


def matricula_web(request):
    template_name = 'matricula_web.html'
    context = {}
    return render(request, template_name, context)


def monitoria(request):
    template_name = 'monitoria.html'
    context = {}
    return render(request, template_name, context)


def pcne(request):
    template_name = 'pcne.html'
    context = {}
    return render(request, template_name, context)


def predios(request):
    template_name = 'predios_unb.html'
    context = {}
    return render(request, template_name, context)


def tranferencia(request):
    template_name = 'transferencia.html'
    context = {}
    return render(request, template_name, context)


def transporte(request):
    template_name = 'transporte.html'
    context = {}
    return render(request, template_name, context)

guias/templates/assistencia_estudantil.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
    <div class="container padding">
        <div class="jumbotron">
            <h1 class="text-center"> Guia de assistência estudantil </h1>

            <div class="paragraph">
                <h4 class="font-weight-bold">O que é a assistência estudantil?</h4>
                <p>É um programa com a finalidade de ampliar as condições de <span class="underline">permanência</span> dos jovens em situação de vulnerabilidade econômica na Universidade Federal.</p>
            </div>

            <div class="paragraph">
                <h4 class="font-weight-bold">Quem é responsável por gerenciar as políticas da assistência na UnB?</h4>
                <p>Compete à Diretoria de Desenvolvimento Social (<span class="underline">DDS</span>) o planejamento, implantação, operacionalização e monitoramento dos programas, projetos e ações da Política de Assistência Estudantil desenvolvidas na Universidade de Brasília. </p>
            </div>

            <div class="paragraph">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <div class="grid-paragraph">
                            <h4 class="font-weight-bold">Onde fica a sede da DDS?</h4>
                            <p>A DDS tem sede no Bloco Eudoro de Souza (<span class="underline">BAES</span>), em frente ao BSAN.</p>
                        </div>

                        <div class="grid-paragraph">
                            <h4 class="font-weight-bold">Quem pode participar da assistência estudantil?</h4>
                            <p>Os estudantes com renda familiar per capita de até <span class="underline">1,5 salário mínimo</span>.</p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <img widht="100%" height="100%" src="{% get_media_prefix %}/guias_img/assistencia/assistencia1.png" alt="">
                    </div>
                </div>
            </div>

            <div class="paragraph">
                <h4>Quais os programas de assistência estudantil?</h4>
                <ul>
                    <li>
                        Bolsa alimentação no Restaurante Universitário (RU):
                        <ul>
                            <li>Estudantes com renda familiar bruta de até 1,5 salário mínimo per capta
                                <span class="underline">não pagam as refeições</span> (café, almoço, jantar).
                                Aos estudantes com ingresso por meio do sistema de
                                cotas, provenientes
                                de escolas públicas com renda familiar bruta igual ou inferior a 1,5 salário
                                mínimo per capita terão acesso imediato à Bolsa Alimentação durante
                                seu primeiro semestre letivo, ainda que não tenham solicitado avaliação
                                de seu Estudo Socioeconômico.
                            </li>
                        </ul>
                    </li>
                    <li>
                        Auxílio Transporte:
                        <ul>
                            <li>
                                Auxílio mensal de <span class="underline">R$ 300,00</span> (durante o período de
                                aulas ou atividade
                                acadêmica) para custear parcialmente as despesas do estudante com o
                                transporte interestadual;
                            </li>
                            <li>
                                OBS: Destinação das vagas para essa modalidade se deve à
                                impossibilidade de acesso integral ao passe livre estudantil do
                                DFTRANS
                            </li>
                        </ul>
                    </li>
                    <li>
                        Moradia: Essa modalidade é voltada para estudantes cujo núcleo familiar resida
                        fora do DF e não possua imóveis no DF e estudantes residentes no DF e entorno
                        que sejam provenientes de regiões com acesso comprovadamente difícil ao seu
                        campus de origem.
                        <ul>
                            <li>
                                Auxílio moradia (pecúnia): auxílio financeiro de R$ 530,00 para ajudar com as despesas de
                                aluguel;
                            </li>
                            <li>
                                Vaga na casa do estudante (CEU)
                            </li>
                            <li>
                                Vaga em apartamento específico na CEU, para
                                pessoas com
                                deficiência (modalidade voltada para pessoas que possuam mobilidade
                                reduzida severa e que tenham comprometimento para exercício da vida
                                de forma independente.)
                            </li>
                        </ul>
                        <span class="text-danger"> *vagas na CEU dependem de disponibilidade</span>
                    </li>

                    <li>Auxílio Socioeconômico: Concessão mensal de auxílio financeiro
                        de <span class="undeline">R$465,00</span> para minimizar desigualdades sociais e ajudar nos estudos.
                    </li>
                    <li>Auxílio Creche: Auxílio financeiro de <span class="underline">R$
                        485,00</span> a estudantes que sejam
                        responsáveis legais e residam com crianças em idade entre <span class="underline">zero e cinco anos
                        incompletos</span>; pagamento mensal mantido durante o recesso letivo.
                    </li>
                    <li>Auxílio emergencial: benefício de <span class="underline">R$
                        465,00</span> destinado a alunos com
                        dificuldades financeiras EMERGENCIAIS que coloquem em risco sua
                        permanência na UnB. O aluno que se aplica para essa modalidade não pode
                        receber benefícios do programa de assistência estudantil.
                    </li>
                    <li>Vale livro: Editora UnB disponibiliza aos
                        estudantes de graduação em situação
                        de vulnerabilidade socioeconômica <span class="underline">05</span> vales por semestre, com <span class="underline">desconto de
                        60%</span> nos livros da Editora.
                    </li>
                    <li>Acesso à língua estrangeira: A UnB idiomas disponibiliza aos estudantes
                        PPAES, em cada semestre letivo, uma <span class="underline">vaga</span> por turma nos <span class="underline">cursos de línguas
                        oferecidos com isenção de mensalidade</span>. As inscrições são realizadas no
                        Programa de Extensão UnB Idiomas, de acordo com critérios e calendário
                        próprios disponíveis na página da <a href="https://www.unbidiomas.unb.br">UnB Idiomas.</a>
                    </li>
                </ul>
            </div>

            
            <div class="paragraph">
                <h4>Como se inscrever nos programas de assistência estudantil?</h4>
                <ol>
                    <li>Pela avaliação socioeconômica: que avalia as condições financeiras do
                        estudante para classificá-lo como apto a
                    </li>
                    <li>Fazer a inscrição da avaliação socioeconômica online no site <a href="https://www.servicos.unb.br/sae">SAEWeb</a>
                        a. Para se inscrever na seleção dos Programas de assistência o estudante
                        deve assinalar a intenção de concorrer ao(s) respectivo(s) Programa(s)
                        no SAEWeb durante o preenchimento da Avaliação Socioeconômica
                    </li>
                    <li>Preencher o formulário com as informações solicitadas</li>
                    <li>Acompanhar o andamento da avaliação socioeconômica através do SAEWeb</li>
                    <li>Assinar o Termo de Concessão (caso seja selecionado) junto ao Serviço de
                        Programas de Desenvolvimento Social (SPS) em data estabelecida no
                        cronograma do edital de avaliação socioeconômica
                    </li>
                    <li>Os candidatos classificados, mas não selecionados ficarão em lista de espera
                        que terá validade até o último dia de aula do respectivo semestre
                    </li>
                </ol>
            </div>
            
            <div class="paragraph">
                <ul>
                    <li>Se houver dúvida, entre em contato com o SPS</li>
                    <li>Em caso de erro tire um print para comprovar</li>
                    <li><span class="underline">A ANÁLISE DA DOCUMENTAÇÃO SERÁ REALIZADA EM PERÍODO
                        ESTABELECIDO NO CRONOGRAMA DO EDITAL do respectivo semestre</span>
                    </li>
                </ul>
            </div>
            
            <div class="paragraph">
                <h4>Qual a documentação exigida para preencher o formulário do SAEWeb?</h4>
                <p>Consultar o edital de avaliação econômica do respectivo semestre. </p>
            </div>
            
            <div class="paragraph">
                <h4>É possível interpor recurso contra o resultado?</h4>
                <p>O estudante que desejar interpor recurso ao resultado preliminar da Avaliação
                    Socioeconômica deverá fazer a solicitação em formulário próprio no SPS do seu
                    campus de origem em prazo estabelecido no cronograma do Edital.</p>
                </div>
                
                <div class="paragraph">
                    <h4>Validade da Avaliação socioeconômica:</h4>
                    <ul>
                        <li>Estudantes nas modalidades Auxílio Moradia e Auxílio Transporte
                            deverão realizar anualmente a renovação para permanência no Programa, a ser regida
                            por Edital específico; Estudante pode ser desligado dessas modalidades se
                            exceder dois semestres do tempo regular de conclusão do seu curso de
                            graduação.
                    </li>
                    <li>A validade da Avaliação Socioeconômica para se manter nos demais programas
                        da assistência estudantil é de 10 (dez) semestres letivos consecutivos.
                    </li>
                    <li>o monitoramento da referida validade de responsabilidade exclusiva do estudante.
                    </li>
                </ul>
            </div>
            
            <div class="paragraph">
                <h4> Renovação da avaliação socioeconômica </h4>
                <p>No décimo semestre de validade da Avaliação Socioeconômica, o
                    estudante que tiver interesse de manter seu vínculo com a Assistência Estudantil deverá
                    submeter-se ao Edital de Avaliação Socioeconômica do semestre da renovação
                    e preencher um novo formulário no SAEWeb enviando os documentos
                    atualizados conforme o Edital vigente à época.</p>
                    
            </div>

            <div class="paragraph">
                <h4>Existe um limite para utilizar os programas da assistência?</h4>
                <p>Os Programas de Assistência Estudantil são acumuláveis com o recebimento de bolsas acadêmicas, porém a soma dos benefícios pecuniários da Assistência Estudantil recebidos pelo estudante não poderá ultrapassar o valor de 1,5 salário mínimo.</p>
            </div>

            <div class="paragraph">
                <p class="font-weight-bold" id="color-cadir">Caso tenha alguma dúvida em como ter acesso aos programas da assistência, leia o
                EDITAL de AVALIAÇÃO SOCIOECONÔMICA que é disponibilizado no site da Diretoria
                de Desenvolvimento Social (DDS) todo semestre ou ligue para a DDS.</p>
            </div>
            

        </div>
    </div>
    {% endblock %}

guias/templates/estrangeiro.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
    <div class="container padding">
        <div class="jumbotron">
            <h1 class="text-center"> Futuro guia de aluno estrangeiro </h1>
        </div>
    </div>
{% endblock %}

guias/templates/fluxo.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
    <div class="container padding">
        <div class="jumbotron">
            <h1 class="text-center"> Futuro fluxo esquematizado </h1>
        </div>
    </div>
{% endblock %}

guias/templates/guias_index_dinamico.html
{% extends 'base.html' %}

{% load static %}
{% block content %}


    <div class="container padding">
        <div class="jumbotron guias">
            <h1 class="text-center">Guias CADir UnB</h1>
            <p class="text-justify"> Aqui podemos encontrar guias para auxiliar sua entrada na UnB. Os guias são
                moldados semestretalmente, para melhor antender a demanda daquele semestre por informações. Têm
                interesse por outros guias? Envie por gentileza suas sugestões na ouvidoria</p>

            {% for guia in Guias %}
                {% if forloop.counter0|divisibleby:3 %}
                    <div class="card-deck text-center justify-content-center">{% endif %}


            <div class="card mb-3" style="max-width: 18rem; border-color: #001652 !important;">
                <div class="card-body text-success">
                    <h5 class="card-title">{{ guia.nome }}</h5>
                    <small style="padding-bottom: 10px;" class="text-muted cat">
                        <i class="far fa-clock text-info"></i> {{ guia.duracao }}minutos
                    </small>
                    <p class="card-text">{{ guia.desc|truncatewords:35 }}</p>
                </div>
                <div class="card-footer bg-transparent" style="border-color: #001652 !important;">
                    <a style="color: #001652; font-size: .9rem;" href="{% url 'guias:guias_show' pk=guia.id %} ">Ler
                        Guia</a>
                </div>
                <div class="card-footer bg-transparent" style="border-color: #001652 !important;">
                    <a style="color: #001652; font-size: .9rem;" href="{% get_media_prefix %}{{ guia.file }}">Baixar
                        Guia</a>
                </div>
            </div>
            {% if forloop.counter|add:3|divisibleby:3 %}</div>{% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

guias/templates/guias_index_estatico.html
{% extends 'base.html' %}

{% load static %}
{% block content %}


    <div class="container padding">
        <div class="jumbotron guias">
            <h1 class="text-center">Guias CADir UnB</h1>
            <p class="text-justify"> {% lorem %}</p>

            <!-- Cartões para os guias estáticos -->

            <div class="card-deck text-center">

                <div class="card mb-3" style="max-width: 18rem; border-color: #001652 !important;">
                    <div class="card-body text-success">
                        <h5 class="card-title">Manual do Calouro</h5>
                        <small style="padding-bottom: 10px;" class="text-muted cat">
                            <i class="far fa-clock text-info"></i> 30 minutos
                        </small>
                        <p class="card-text">Quick sample text to create the card title and make up the body of the
                            card's content.</p>
                    </div>
                    <div class="card-footer bg-transparent" style="border-color: #001652 !important;">
                        <a style="color: #001652; font-size: .9rem;" href="{% url 'guias:manual_do_calouro' %}">Ler
                            Guia</a>
                    </div>
                </div>

                <div class="card mb-3" style="max-width: 18rem; border-color: #001652 !important;">
                    <div class="card-body text-success">
                        <h5 class="card-title"> Crédito, fluxo e menção </h5>
                        <small style="padding-bottom: 10px;" class="text-muted cat">
                            <i class="far fa-clock text-info"></i> 30 minutos
                        </small>
                        <p class="card-text">Esqueceu quantos créditos precisa para se formar? Esqueceu o período máximo
                            e mínimo de permanência no curso? Esqueceu o fluxo? Quer conhecer a fórmula que calcula o
                            IRA? E está com preguiça de tirar essas dúvidas no MW? Esse guia foi feito para você! </p>
                    </div>
                    <div class="card-footer bg-transparent" style="border-color: #001652 !important;">
                        <a style="color: #001652; font-size: .9rem;" href="{% url 'guias:fluxo' %}">Ler Guia</a>
                    </div>
                </div>

                <div class="card mb-3" style="max-width: 18rem; border-color: #001652 !important;">
                    <div class="card-body text-success">
                        <h5 class="card-title">Monitoria</h5>
                        <small style="padding-bottom: 10px;" class="text-muted cat">
                            <i class="far fa-clock text-info"></i> 5 minutos
                        </small>
                        <p class="card-text">Sabe aquela matéria que você se apaixonou? Gostou da didática do professor
                            e quer ajudá-lo com algumas tarefas? Está querendo corrigir resenhas, fichamentos, fazer
                            chamada, ou auxiliar os professores? Bom, aproveite esse guia para retirar as suas dúvidas.
                            Fique atento aos prazos para se inscrever na monitoria e não esqueça de preencher o
                            formulário da coordenação! </p>
                    </div>
                    <div class="card-footer bg-transparent" style="border-color: #001652 !important;">
                        <a style="color: #001652; font-size: .9rem;" href="{% url 'guias:monitoria' %}">Ler Guia</a>
                    </div>
                </div>

                <div class="card mb-3" style="max-width: 18rem; border-color: #001652 !important;">
                    <div class="card-body text-success">
                        <h5 class="card-title">Matrícula Web</h5>
                        <small style="padding-bottom: 10px;" class="text-muted cat">
                            <i class="far fa-clock text-info"></i> 30 minutos
                        </small>
                        <p class="card-text">Utilize esse guia para entender um pouco mais sobre o Matrícula Web, sobre
                            os procedimentos da matrícula, do ajuste… Não fique mais perdido antes do semestre começar!
                            Leia essas dicas e atente-se aos prazos que são fornecidos no Calendário Universitário de
                            Graduação. </p>
                    </div>
                    <div class="card-footer bg-transparent" style="border-color: #001652 !important;">
                        <a style="color: #001652; font-size: .9rem;" href="{% url 'guias:matricula_web' %}">Ler Guia</a>
                    </div>
                </div>

            </div>

            <div class="card-deck text-center">

                <div class="card mb-3" style="max-width: 18rem; border-color: #001652 !important;">
                    <div class="card-body text-success">
                        <h5 class="card-title">Assistência Estudantil</h5>
                        <small style="padding-bottom: 10px;" class="text-muted cat">
                            <i class="far fa-clock text-info"></i> 7 minutos
                        </small>
                        <p class="card-text">Quick sample text to create the card title and make up the body of the
                            card's content.</p>
                    </div>
                    <div class="card-footer bg-transparent" style="border-color: #001652 !important;">
                        <a style="color: #001652; font-size: .9rem;" href="{% url 'guias:assistencia_estudantil' %}">Ler
                            Guia</a>
                    </div>
                </div>

                <div class="card mb-3" style="max-width: 18rem; border-color: #001652 !important;">
                    <div class="card-body text-success">
                        <h5 class="card-title">Transporte</h5>
                        <small style="padding-bottom: 10px;" class="text-muted cat">
                            <i class="far fa-clock text-info"></i> 30 minutos
                        </small>
                        <p class="card-text">Quick sample text to create the card title and make up the body of the
                            card's content.</p>
                    </div>
                    <div class="card-footer bg-transparent" style="border-color: #001652 !important;">
                        <a style="color: #001652; font-size: .9rem;" href="{% url 'guias:transporte' %}">Ler Guia</a>
                    </div>
                </div>

                <div class="card mb-3" style="max-width: 18rem; border-color: #001652 !important;">
                    <div class="card-body text-success">
                        <h5 class="card-title">Aluno PCNE</h5>
                        <small style="padding-bottom: 10px;" class="text-muted cat">
                            <i class="far fa-clock text-info"></i> 30 minutos
                        </small>
                        <p class="card-text">A FD quer receber você, estudante com deficiência, da melhor forma
                            possível. Por isso, preparamos um guia com informações preciosas que nem sempre te contam.
                            Nós estamos aqui para te ajudar a reivindicar pelos seus direitos, queremos uma UnB
                            inclusiva e acessível para todos a começar pela informação! </p>
                    </div>
                    <div class="card-footer bg-transparent" style="border-color: #001652 !important;">
                        <a style="color: #001652; font-size: .9rem;" href="{% url 'guias:pcne' %}">Ler Guia</a>
                    </div>
                </div>

                <div class="card mb-3" style="max-width: 18rem; border-color: #001652 !important;">
                    <div class="card-body text-success">
                        <h5 class="card-title">Aluno de Transferência</h5>
                        <small style="padding-bottom: 10px;" class="text-muted cat">
                            <i class="far fa-clock text-info"></i> 30 minutos
                        </small>
                        <p class="card-text">Quick sample text to create the card title and make up the body of the
                            card's content.</p>
                    </div>
                    <div class="card-footer bg-transparent" style="border-color: #001652 !important;">
                        <a style="color: #001652; font-size: .9rem;" href="{% url 'guias:transferencia' %}">Ler Guia</a>
                    </div>
                </div>

            </div>

            <div class="card-deck text-center">

                <div class="card mb-3" style="max-width: 18rem; border-color: #001652 !important;">
                    <div class="card-body text-success">
                        <h5 class="card-title">Aluno Estrangeiro</h5>
                        <small style="padding-bottom: 10px;" class="text-muted cat">
                            <i class="far fa-clock text-info"></i> 30 minutos
                        </small>
                        <p class="card-text">Quick sample text to create the card title and make up the body of the
                            card's content.</p>
                    </div>
                    <div class="card-footer bg-transparent" style="border-color: #001652 !important;">
                        <a style="color: #001652; font-size: .9rem;" href="{% url 'guias:aluno_estrangeiro' %}">Ler
                            Guia</a>
                    </div>
                </div>

                <div class="card mb-3" style="max-width: 18rem; border-color: #001652 !important;">
                    <div class="card-body text-success">
                        <h5 class="card-title">Prédios da UnB</h5>
                        <small style="padding-bottom: 10px;" class="text-muted cat">
                            <i class="far fa-clock text-info"></i> 3 minutos
                        </small>
                        <p class="card-text">Você sabe quais os principais prédios perto da FD? Aproveite esse guia para
                            conhecer parte do nosso país UnB e de quebra apreciar fotos muito bonitas! Quem sabe esse
                            guia não te inspira a explorar a arquitetura da nossa Universidade? Ou a se perder pelo
                            campus do ilustre Darcy Ribeiro?</p>
                    </div>
                    <div class="card-footer bg-transparent" style="border-color: #001652 !important;">
                        <a style="color: #001652; font-size: .9rem;" href="{% url 'guias:predios_unb' %}">Ler Guia</a>
                    </div>
                </div>

            </div>


            <h2 class="text-center">Gostou? Encontre mais guias abaixo!</h2>
            <br>
            <!-- Guias que serão links externos -->
            <div class="list-group">
                {% for guias in Guias %}
                    <!-- Redireciona para o dowload do arquivo ou o link ou nada -->
                    <a href="{% if guias.file %} {% get_media_prefix %}{{ guias.file }}
                            {% elif guias.link %} {{ guias.link }}
                            {% else %} # {% endif %}" target="_blank"
                       class="list-group-item list-group-item-action">
                        {% if guias.file or guias.link %}
                            <span class="text-primary"> {{ guias.nome }} </span>
                        {% else %}
                            <span class="text-muted"> {{ guias.nome }} </span>
                        {% endif %}
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}