SiteCaDir/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views import defaults
from django.urls import re_path
from django.views.static import serve

def custom_page_not_found(request):
    return defaults.page_not_found(request, None)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('core.urls', namespace='core')),
    path('programas/', include('programas.urls', namespace='programas')),
    path('ouvidoria/', include('ouvidoria.urls', namespace='ouvidoria')),
    path('eventos/', include('eventos.urls', namespace='eventos')),
    path('guias/', include('guias.urls', namespace='guias')),
    path('institucional/', include('institucional.urls', namespace='institucional')),

    # Debbuging url
    path('404/', custom_page_not_found),
]

urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

core/urls.py
from django.urls import path, include
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.main_page, name='main'),
]

eventos/urls.py
from django.urls import path, include
from eventos import views

app_name = 'eventos'

urlpatterns = [
    # Index Path
    path('', views.index, name='eventos_index'),
    #show Path
    path('<int:pk>', views.show, name='show')
]

guias/urls.py
from django.urls import path, include
from guias import views

app_name = 'guias'

urlpatterns = [
    # Index Path
    path('', views.index, name='guias_index'),
    # Show Path
    path('<int:pk>', views.show, name='guias_show'),
    path('assistencia_estudantil', views.assistencia_estudantil, name='assistencia_estudantil'),
    path('aluno_estrangeiro', views.estrangeiro, name='aluno_estrangeiro'),
    path('fluxo', views.fluxo, name='fluxo'),
    path('manual_do_calouro', views.calouro, name='manual_do_calouro'),
    path('matricula_web', views.matricula_web, name='matricula_web'),
    path('monitoria', views.monitoria, name='monitoria'),
    path('pcne', views.pcne, name='pcne'),
    path('predios_unb', views.predios, name='predios_unb'),
    path('transferencia', views.tranferencia, name='transferencia'),
    path('transporte', views.transporte, name='transporte')
]

institucional/urls.py
from django.urls import path, include
from institucional import views

app_name = 'institucional'

urlpatterns = [
    # Index Path
    path('', views.index, name='institucional_index'),
    # Path Postagens
    path('postagens', views.postagens_index, name='postagens_index'),
    path('postagem/<str:pk>', views.postagem_show, name='postagem_show'),
    # Path Historico
    path('historico', views.historico, name='institucional_historico'),
    # Path Prestação de cotnas
    path('prestacao_conta', views.contas, name='institucional_contas'),
    # Path atas
    path('atas', views.atas, name='institucional_atas')
]

programas/urls.py
from django.urls import path, include
from programas import views

app_name = 'programas'

urlpatterns = [
    # Index Path
    path('', views.index, name='programas_index'),
    # Show Path
    path('<int:pk>', views.show, name='show')
]

core/models.py
from django.db import models


# Create your models here.

class Fotos(models.Model):
    nome = models.CharField('Nome', max_length=60, help_text='Nome só para lembrar qual foto é')
    foto = models.ImageField('Foto', upload_to='fotos_principal')

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name_plural = "Fotos"
        verbose_name = "Foto"

    def delete(self, *args, **kwargs):
        print(self.nome)
        if self.nome == "1 Slider" or self.nome == "2 Slider" or self.nome == "3 Slider" \
                or self.nome == "1 Foto Divisão" or self.nome == "2 Foto Divisão":
            return
        else:
            super(Fotos, self).delete(*args, **kwargs)

core/views.py
from django.shortcuts import render
from programas.models import Programa
from eventos.models import Evento
from guias.models import Guia
from .models import Fotos
# Create your views here.

def main_page(request):
    template_name  = 'main_page.html'
    context = {
        "Programas": Programa.objects.order_by('?')[:4],
        "Eventos": Evento.objects.order_by('start_day')[:3],
        "Guias": Guia.objects.order_by('?')[:4],
        "1Slider": Fotos.objects.filter(nome='1 Slider').get(),
        "2Slider": Fotos.objects.filter(nome='2 Slider').get(),
        "3Slider": Fotos.objects.filter(nome='3 Slider').get(),
        "1FotoDivisao": Fotos.objects.filter(nome='1 Foto Divisão').get(),
        "2FotoDivisao": Fotos.objects.filter(nome='2 Foto Divisão').get(),
    }
    return render(request, template_name, context)

core/templates/main_page.html
{% extends 'base.html' %}

{% load static %}
{% load bleach_tags %}
{% block content %}

    <!-- ***********************MAIN SLIDER****************************** -->

    <div class="carousel slide carousel-fade" data-interval="3000" data-ride="carousel" id="carouselExampleIndicators">
        <ol class="carousel-indicators">
            <li class="active" data-slide-to="0" data-target="#carouselExampleIndicators"></li>
            <li data-slide-to="1" data-target="#carouselExampleIndicators"></li>
            <li data-slide-to="2" data-target="#carouselExampleIndicators"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div id="fisrt-slider" class="carousel-item active"
                 style="background-image:linear-gradient(rgba(255, 255, 255, 0.25), rgba(255,255,255,0.25)), url(
                         {% get_media_prefix %}{{ 1Slider.foto }});
                         background-size: cover">
                <div class="carousel-caption text-center">
                    <h1>Direito UnB</h1>
                    <h3>Centro Acadêmico</h3>
                </div>
            </div>
            <div id="second-slider" class="carousel-item"
                 style="background-image:linear-gradient(rgba(255, 255, 255, 0.25), rgba(255,255,255,0.25)), url(
                         {% get_media_prefix %}{{ 2Slider.foto }});
                         background-size: cover">
                <div class="carousel-caption text-center">
                    <h1>Direito UnB</h1>
                    <h3>Centro Acadêmico</h3>
                </div>
            </div>
            <div id="third-slider" class="carousel-item"
                 style="background-image:linear-gradient(rgba(255, 255, 255, 0.25), rgba(255,255,255,0.25)), url(
                         {% get_media_prefix %}{{ 3Slider.foto }});
                         background-size: cover">
                <div class="carousel-caption text-center">
                    <h1>Direito UnB</h1>
                    <h3>Centro Acadêmico</h3>
                </div>
            </div>
        </div>
        <a href="#carouselExampleIndicators" class="carousel-control-prev" role="button" data-slide="prev"
           onclick="$('#myCarousel').carousel('prev')">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        </a>
        <a href="#carouselExampleIndicators" class="carousel-control-next" role="button" data-slide="next"
           onclick="$('#myCarousel').carousel('next')">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
        </a>
    </div>
    <!-- *********************** END MAIN SLIDER ************************ -->
    <!-- Texto que fica abaixo do cartão de visitas -->

    <div class="padding">
        <div class="container">
            <div class="text-center">
                <h2 class="">O que é o Centro Acadêmico de Direito?</h2>
            </div>
            <p align="justify" class="custom-paragraph">O Centro Acadêmico de Direito da Universidade de Brasília é o
                órgão representativo de todas/os estudantes de Direito da UnB. Trata-se de associação independente e
                plural, fundada em 25 de novembro de 1993 e filiada à União Nacional dos Estudantes. Seu principal
                objetivo é representar e defender os interesses discentes. Ao desenvolver atividades acadêmicas,
                sociais, políticas, jurídicas, culturais e recreativas, visa enriquecer a formação das/os estudantes de
                Direito. Além disso, objetiva fortalecer e mobilizar as entidades estudantis. Sobretudo, traduz-se em
                instrumento de luta por uma Universidade pública, de qualidade, e pela defesa de direitos, da igualdade
                e da justiça social.</p>
            <div class="text-center">
                <a class="btn btn-primary" href="{% url 'institucional:institucional_index' %}">Ler Mais</a>
            </div>
        </div>
    </div>

    <!-- Area que seria uma preview dos guias -->
    <div class="padding">
        <div class="container guias">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 py-2">
                    <a href="{% url 'guias:guias_show' pk=8 %}">
                        <h4>Como usar o Matrícula Web</h4>
                    </a>
                    <hr class="socket">
                    <p align="justify">Utilize esse guia para entender um pouco mais sobre o Matrícula Web, sobre os
                        procedimentos da matrícula, do ajuste… Não fique mais perdido antes do semestre começar!
                        Leia essas dicas e atente-se aos prazos que são fornecidos no Calendário Universitário de
                        Graduação.</p>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 py-2">
                    <img class="img-responsive" src="{% get_media_prefix %}mw.jpeg">
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 py-2">
                    <a href="{% url 'guias:guias_show' pk=10 %}">
                        <h4>Guia dos prédios da UnB</h4>
                    </a>
                    <hr class="socket">
                    <p align="justify">Você sabe quais os principais prédios perto da FD? Aproveite esse guia para
                        conhecer parte do nosso país UnB e de quebra apreciar fotos muito bonitas! Quem sabe esse
                        guia não te inspira a explorar a arquitetura da nossa Universidade? Ou a se perder pelo campus
                        do
                        ilustre Darcy Ribeiro?</p>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 py-2">
                    <img src="{% get_media_prefix %}guias_img/predios/fd_1.png">
                </div>
            </div>
            <br>
            <div class="text-center ver-mais">
                <a class="btn btn-primary" href="{% url 'guias:guias_index' %}">Mais Guias Estudantis</a>
            </div>
        </div>
    </div>

    <!-- Imagem de espaçamento -->
    <div class="fixed">
        <img class="img-fluid" src="{% get_media_prefix %}{{ 1FotoDivisao.foto }}">
    </div>

    <!-- Apresentação genérica sobre os programas do direito -->
    <div class="padding">
        <div class="container">
            <div class="text-center">
                <h2 class="">Programas da Faculdade de Direito - UnB</h2>
            </div>
            <p align="justify" class="custom-paragraph">O corpo discente da Faculdade de Direito é bastante ativo, há
                uma diversidade de programas de iniciativa estudantil, estes permitem que os alunos se engajem em
                atividades de extensão, um dos componentes do tripé que constitui a proposta inicial pensada para a
                Universidade de Brasília, empresa júnior e atlética. Essas iniciativas expandem os horizontes e
                enriquecem a vivência acadêmica.</p>
        </div>
    </div>

    <!-- Programas do direito -->
    <div>
        <section id="responsive">
            <div class="container-fluid">
                <div class="card-deck">
                    {% for programa in Programas %}
                        <div data-aos="fade-up" class="card" style="width: 18rem;">
                            <a href="{% url 'programas:show' pk=programa.id %}">
                                <img alt="Card image cap" class="card-img-top"
                                     style="border-radius: 50%;"
                                     src="{% get_media_prefix %}{{ programa.logo }}" height="291.75" width="291.75">
                            </a>
                            <div class="card-body">
                                <h5 class="card-title text-center font-weight-bold">{{ programa.nome }}</h5>
                                <p align="justify">{{ programa.text|bleach|truncatewords:25 }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="text-center ver-mais">
                    <a class="btn btn-primary" href="{% url 'programas:programas_index' %}">Ver Mais Programas</a>
                </div>
            </div>
        </section>
    </div>

    <div class="fixed">
        <img class="img-fluid" src="{% get_media_prefix %}{{ 2FotoDivisao.foto }}">
    </div>

    <div class="padding">
        <div class="container">
            <div class="text-center">
                <h2 class=""> Eventos do Direito UnB</h2>
            </div>
            <p align="justify" class="custom-paragraph">Sabemos que a formação de um bom jurista vai muito além da sala
                de aula. Por mais importantes que sejam os conteúdos ministrados, atividades extracurriculares são
                essenciais não só na formação acadêmica, mas de um cidadão. Tendo isso em mente, o Centro Acadêmico de
                Direito criou um espaço para que os estudantes possam se inteirar dos diversos eventos relacionados ao
                Direito que ocorrem semestralmente na Universidade. Então marque na sua agenda e fique por dentro das
                diversas atividades que ocorrem pelo campus!</p>
        </div>
    </div>

    <!-- Disposição alternativa dos eventos -->
    <div class="container eventos">
        <div class="row">
            {% for evento in Eventos %}
                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 py-2">
                    <a href="{% url 'eventos:show' pk=evento.id %}"><h4>{{ evento.title }}</h4><a>
                        <hr class="socket">
                        <p allign="justify">{{ evento.desc | truncatewords:20 }}</p>
                        <div>
                            {% if evento.start_day == evento.end_day %}
                                <i class="fas fa-calendar-week"></i> {{ evento.start_day }} <br>
                            {% else %}
                                <i class="fas fa-calendar-week"></i> {{ evento.start_day }} -
                                {{ evento.end_day }}<br>
                            {% endif %}
                            {% if evento.isAllDay %}
                                <i class="fas fa-map-marker-alt"></i> {{ evento.local }}
                            {% else %}
                                {% if evento.end %}
                                    <i class="far fa-clock"></i> {{ evento.start }} -
                                    {{ evento.end|default_if_none:"não informado" }}
                                {% else %}
                                    <i class="far fa-clock"></i> {{ evento.start }}
                                {% endif %}
                                <i class="fas fa-map-marker-alt"></i> {{ evento.local }}
                            {% endif %}
                        </div>
                </div>
            {% endfor %}
        </div>
        <br>
        <div class="text-center ver-mais">
            <a class="btn btn-primary" href="{% url 'eventos:eventos_index' %}">Mais Eventos</a>
        </div>
    </div>

{% endblock %}