SiteCaDir/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views import defaults
from django.urls import re_path
from django.views.static import serve

def custom_page_not_found(request):
    return defaults.page_not_found(request, None)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('core.urls', namespace='core')),
    path('programas/', include('programas.urls', namespace='programas')),
    path('ouvidoria/', include('ouvidoria.urls', namespace='ouvidoria')),
    path('eventos/', include('eventos.urls', namespace='eventos')),
    path('guias/', include('guias.urls', namespace='guias')),
    path('institucional/', include('institucional.urls', namespace='institucional')),

    # Debbuging url
    path('404/', custom_page_not_found),
]

urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

core/urls.py
from django.urls import path, include
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.main_page, name='main'),
]

eventos/urls.py
from django.urls import path, include
from eventos import views

app_name = 'eventos'

urlpatterns = [
    # Index Path
    path('', views.index, name='eventos_index'),
    #show Path
    path('<int:pk>', views.show, name='show')
]

guias/urls.py
from django.urls import path, include
from guias import views

app_name = 'guias'

urlpatterns = [
    # Index Path
    path('', views.index, name='guias_index'),
    # Show Path
    path('<int:pk>', views.show, name='guias_show'),
    path('assistencia_estudantil', views.assistencia_estudantil, name='assistencia_estudantil'),
    path('aluno_estrangeiro', views.estrangeiro, name='aluno_estrangeiro'),
    path('fluxo', views.fluxo, name='fluxo'),
    path('manual_do_calouro', views.calouro, name='manual_do_calouro'),
    path('matricula_web', views.matricula_web, name='matricula_web'),
    path('monitoria', views.monitoria, name='monitoria'),
    path('pcne', views.pcne, name='pcne'),
    path('predios_unb', views.predios, name='predios_unb'),
    path('transferencia', views.tranferencia, name='transferencia'),
    path('transporte', views.transporte, name='transporte')
]

ouvidoria/urls.py
from django.urls import path, include
from ouvidoria import views

app_name = 'ouvidoria'

urlpatterns = [
    # Index Path
    path('', views.ouvidoria, name='ouvidoria'),
]

programas/urls.py
from django.urls import path, include
from programas import views

app_name = 'programas'

urlpatterns = [
    # Index Path
    path('', views.index, name='programas_index'),
    # Show Path
    path('<int:pk>', views.show, name='show')
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, shrink-to-fit=no" name="viewport">
    <meta content="ie=edge" http-equiv="X-UA-Compatible">
    <meta name="keywords" content="Direito, unb, fd, faculdade,universidade,Brasília, cadir, centro, acadêmico, cadir, guias, calouro, mw, matricula, web, pcd, ru, icc, minhocao">
    <meta name="robots" content="index, follow">
    <meta name="description" content="Nós do Centro Acadêmico de Direito da UnB acreditamos que informação é poder, por isso esse site foi criado! Encontre aqui os principais eventos que podem interessar os estudantes da Faculdade de Direito, guias que vão te salvar pela UnB, nosso passado como instituição e muito mais. Sabendo sobre as dificuldades de achar informações espalhadas por inúmeras redes, decidimos reuni-las nessa plataforma!"/>
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" rel="stylesheet">
    <link rel="icon" href="../media/CADir_logo.png">
    <link rel="canonical" href="https://www.cadirunb.com.br">	
    <title>CADir UnB</title>

    <!-- Full Callendar -->
    <link rel='stylesheet' href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.css" />

    <!-- Font Awesome -->
    <script crossorigin="anonymous" defer
            integrity="sha384-DJ25uNYET2XCl5ZF++U8eNxPWqcKohUUBUpKGlNLMchM7q4Wjg2CUpjHLaL8yYPH"
            src="https://use.fontawesome.com/releases/v5.8.2/js/all.js"></script>

    <!-- Bootstrap -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"/>

    <!-- Our css -->
    <link rel="stylesheet" href="{% static "css/main_page.css" %}"/>
    <link rel="stylesheet" href="{% static "css/mini_timeline.css" %}"/>
    <link rel="stylesheet" href="{% static "css/programas.css" %}"/>
    <link rel="stylesheet" href="{% static "css/eventos.css" %}"/>
    <link rel="stylesheet" href="{% static "css/templates.css" %}"/>
    <link rel="stylesheet" href="{% static "css/guias.css" %}"/>

    <!-- AOS Library-->
    <link href="https://unpkg.com/aos@next/dist/aos.css" rel="stylesheet"/>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

</head>
<body>
<div class="container-fluid">
    <nav class="navbar fixed-top navbar-expand-lg navbar-light stroke">
        <a class="navbar-brand" href="{% url 'core:main' %}">
            <img class="img-fluid" src="{% get_media_prefix %}CADir_logo.png">
        </a>

        <button class="navbar-toggler" data-target="#collapsibleNavbar" data-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item px-2">
                    <a class="nav-link {% if request.resolver_match.url_name == 'main' %}active{% endif %}"
                       href="{% url 'core:main' %}">
                        Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item px-2">
                    <a class="nav-link {% if request.resolver_match.url_name == 'institucional_index' %}active{% endif %}"
                       href="{% url 'institucional:institucional_index' %}">
                        Institucional
                    </a>
                </li>
                <li class="nav-item px-2">
                    <a class="nav-link {% if request.resolver_match.url_name == 'eventos_index' %}active{% endif %}"
                       href="{% url 'eventos:eventos_index' %}">
                        Eventos
                    </a>
                </li>
                <li class="nav-item px-2">
                    <a class="nav-link {% if request.resolver_match.url_name == 'guias_index' %}active{% endif %}"
                       href="{% url 'guias:guias_index' %}">
                        Guias
                    </a>
                </li>
                <li class="nav-item px-2">
                    <a class="nav-link {% if request.resolver_match.url_name == 'programas_index' %}active{% endif %}"
                       href="{% url 'programas:programas_index' %}">
                        Programas
                    </a>
                </li>
                <li class="nav-item px-2">
                    <a class="nav-link {% if request.resolver_match.url_name == 'ouvidoria' %}active{% endif %}"
                       href="{% url 'ouvidoria:ouvidoria' %}">
                        Ouvidoria
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://momentjs.com/downloads/moment.min.js"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.js'></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/locale/pt-br.js"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js'></script>
<script src='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js'></script>


{% block content %}{% endblock %}

<footer class="bg-dark">
    <div class="row justify-content-center">
        <div class="col-md-5 text-center">
            <h4>CADir UnB</h4>
            <p>Gestão 2019-2020</p>
            <p>
                <a tagert="_blank"
                   href="https://www.google.com.br/maps/place/Faculdade+de+Direito+da+Universidade+de+Bras%C3%ADlia/@-15.7595555,-47.8745767,17z/data=!3m1!4b1!4m5!3m4!1s0x935a3bb7f33f7907:0xecb7469b111b9d00!8m2!3d-15.7595555!4d-47.8723827">
                    <i class="fas fa-map-marker-alt"></i>
                </a>
                Faculdade de Direito, Campus Darcy Ribeiro Asa Norte
            </p>
            <h5><strong>Contatos</strong></h5>
            <p>unb.cadir@gmail.com</p>
            <a href="https://www.facebook.com/centroacademicodedireitounb/?ref=br_rs">
                <i class="fab fa-facebook-square"></i>
            </a>
            <a href="https://instagram.com/cadirunb?igshid=bwzxl135vajk">
                <i class="fab fa-instagram"></i>
            </a>
        </div>
        <hr class="socket">
            {% comment %} <h5>Powered by Switch Dreams &copy;</h5> {% endcomment %}
        <a class="nounderline" href="https://switchdreams.pythonanywhere.com">
            <h5>Powered by Switch Dreams &copy;</h5>
        </a>

    </div>
</footer>

<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script>

    AOS.init({ // Global settings:
        disable: false, // accepts following values: 'phone', 'tablet', 'mobile', boolean, expression or function
        startEvent: 'DOMContentLoaded', // name of the event dispatched on the document, that AOS should initialize on
        initClassName: 'aos-init', // class applied after initialization
        animatedClassName: 'aos-animate', // class applied on animation
        useClassNames: false, // if true, will add content of `data-aos` as classes on scroll
        disableMutationObserver: false, // disables automatic mutations' detections (advanced)
        debounceDelay: 50, // the delay on debounce used while resizing window (advanced)
        throttleDelay: 99,
        // the delay on throttle used while scrolling the page (advanced)


        // Settings that can be overridden on per-element basis, by `data-aos-*` attributes:
        offset: 120, // offset (in px) from the original trigger point
        delay: 0, // values from 0 to 3000, with step 50ms
        duration: 400, // values from 0 to 3000, with step 50ms
        easing: 'ease', // default easing for AOS animations
        once: false, // whether animation should happen only once - while scrolling down
        mirror: false, // whether elements should animate out while scrolling past them
        anchorPlacement: 'top-bottom', // defines which position of the element regarding to window should trigger the animation

    });
</script>
<script src="{% static 'js/main.js' %}"></script>

{% comment %} <script crossorigin="anonymous" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script crossorigin="anonymous" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script crossorigin="anonymous" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script> {% endcomment %}
{% comment %} <script src="{% static 'js/calendar.js' %}"></script> {% endcomment %}
</body>
</html>

templates/error.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
    <div class="text-center">
        <div class="errorcode">
            {% block errocode %}
            {% endblock %}
        </div>


        <img src="{% get_media_prefix %}balance.svg" alt="Imagem da Balança" height="200px">


        <p class="lead"> OPS! Aconteceu algo de errado </p>
        <p> Navegue pelas outras páginas do site </p>


    </div>
{% endblock %}