SiteCaDir/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views import defaults
from django.urls import re_path
from django.views.static import serve

def custom_page_not_found(request):
    return defaults.page_not_found(request, None)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('core.urls', namespace='core')),
    path('programas/', include('programas.urls', namespace='programas')),
    path('ouvidoria/', include('ouvidoria.urls', namespace='ouvidoria')),
    path('eventos/', include('eventos.urls', namespace='eventos')),
    path('guias/', include('guias.urls', namespace='guias')),
    path('institucional/', include('institucional.urls', namespace='institucional')),

    # Debbuging url
    path('404/', custom_page_not_found),
]

urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

core/urls.py
from django.urls import path, include
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.main_page, name='main'),
]

institucional/urls.py
from django.urls import path, include
from institucional import views

app_name = 'institucional'

urlpatterns = [
    # Index Path
    path('', views.index, name='institucional_index'),
    # Path Postagens
    path('postagens', views.postagens_index, name='postagens_index'),
    path('postagem/<str:pk>', views.postagem_show, name='postagem_show'),
    # Path Historico
    path('historico', views.historico, name='institucional_historico'),
    # Path Prestação de cotnas
    path('prestacao_conta', views.contas, name='institucional_contas'),
    # Path atas
    path('atas', views.atas, name='institucional_atas')
]

institucional/models.py
from django.core.exceptions import ValidationError
from django.db import models


# Create your models here.

# Model relacionada a postagens(Estágios, notas)
class Postagem(models.Model):
    nome = models.CharField('Nome', max_length=60, unique=True)
    desc = models.CharField('Descrição', max_length=300, help_text="Descrição abreviada(até 300 caracteres)")

    text = models.TextField('Postagem')

    created_at = models.DateTimeField('created at', auto_now_add=True)
    updated_at = models.DateTimeField('updated at', auto_now=True)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = "Postagem"
        verbose_name_plural = "Postagens"

# Model relacionada as prestações de conta
class PrestacaoDeContas(models.Model):
    nome = models.CharField('Nome', max_length=60, help_text='Nome que aparecerá no site(Institucional)')
    # File para dowload
    file = models.FileField('Arquivo', upload_to='prestacao_de_contas_pdf')

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name_plural = "Prestações de Conta"
        verbose_name = "Prestação de conta"


# Model relacionada as prestações de conta
class Atas(models.Model):
    nome = models.CharField('Nome', max_length=60, help_text='Nome que aparecerá no site(Institucional)')
    # File para dowload
    file = models.FileField('Arquivo', upload_to='atas_pdf')

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name_plural = "Atas"
        verbose_name = "Ata"


# Model relacionada ao Texto do histórico do CADir
class TextoHistorico(models.Model):
    texto = models.TextField('Texto', help_text='Texto no qual se encontra no ver mais do histórico do CADir')

    def __str__(self):
        return "Texto do histórico do CADir"

    def save(self, *args, **kwargs):
        if TextoHistorico.objects.exists() and not self.pk:
            # if you'll not check for self.pk
            # then error will also raised in update of exists model
            raise ValidationError('Só pode ser criado um Texto sobre o histórico do CADir/Edite o que já existe')
        return super(TextoHistorico, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Texto do histórico do CADir"
        verbose_name = "Texto do histórico do CADir"


# Logos das gestões anteriores
class Logos(models.Model):
    nome = models.CharField('Nome', max_length=50, help_text='Nome da gestão correspondente')
    ano_inicial = models.CharField('Ano de início', max_length=4, help_text='Ano em que a gestão iniciou o mandato')
    ano_final = models.CharField('Ano de término', max_length=4, help_text='Ano em que a gestão encerrou o mandato')
    logo = models.ImageField('Logo', help_text='Logo da gestão correspondente')

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name_plural = "Logos"
        verbose_name = "Logo"


# Model Relacionado as estatutos
class Estatuto(models.Model):
    nome = models.CharField('Nome', max_length=60, help_text='Nome que aparecerá no site(Institucional)')
    # File para dowload
    file = models.FileField('Arquivo', upload_to='estato')

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name_plural = "Estatutos"
        verbose_name = "Estatuto"

institucional/views.py
from django.shortcuts import render
from .models import Postagem, TextoHistorico, PrestacaoDeContas, Atas, Logos, Estatuto
from datetime import datetime
from django.utils import timezone
from django.core.paginator import Paginator


# Create your views here.

def index(request):
    template_name = 'institucional_index.html'
    context = {
        "Postagens": Postagem.objects.order_by('-created_at')[:3],
        "Estatutos": Estatuto.objects.all(),
        "Hoje": timezone.now()
    }
    return render(request, template_name, context)


def postagens_index(request):
    template_name = 'postagens_index.html'
    postagem_list = Postagem.objects.order_by('-created_at')
    paginator = Paginator(postagem_list, 10)

    page = request.GET.get('page')
    postagens = paginator.get_page(page)
    context = {
        "Postagens": postagens,
        "Hoje": timezone.now()
    }
    return render(request, template_name, context)


def postagem_show(request, **kwargs):
    template_name = 'postagem_show.html'
    context = {
        "Postagem": Postagem.objects.filter(nome=kwargs['pk']).get(),
        "Hoje": timezone.now()
    }
    return render(request, template_name, context)

def historico(request):
    template_name = 'institucional_historico.html'
    context = {
        "historico" : TextoHistorico.objects.all().get(),
        "logos" : Logos.objects.all()
    }
    return render(request, template_name, context)

def atas(request):
    template_name = 'institucional_atas.html'
    context = {
        "Atas" : Atas.objects.all(),
    }
    return render(request, template_name, context)

def contas(request):
    template_name = 'institucional_contas.html'
    context = {
        'Contas': PrestacaoDeContas.objects.all()
    }
    return render(request, template_name, context)

institucional/templates/institucional_atas.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
    <div class="container padding">
        <div class="jumbotron">
            <h1 class="text-center">Atas de reunião</h1>
            <div class="list-group">
                {% if Atas %}
                    {% for ata in Atas %}
                        <a href="{% get_media_prefix %}{{ ata.file }}" target="_blank"
                           class="list-group-item list-group-item-action">
                            <span class="text-primary"> {{ ata.nome }} </span>
                        </a>
                    {% endfor %}
                {% else %}
                    <h2 class="text-center text-warning"> Nenhuma ata adicionada</h2>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

institucional/templates/institucional_contas.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
    <div class="container padding">
        <div class="jumbotron">
            <h1 class="text-center"> Prestação de Contas</h1>
            <div class="list-group">
                {% if Contas %}
                    {% for conta in Contas %}
                        <a href="{% get_media_prefix %}{{ conta.file }}" target="_blank"
                           class="list-group-item list-group-item-action">
                            <span class="text-primary"> {{ conta.nome }} </span>
                        </a>

                    {% endfor %}
                {% else %}
                    <h2 class="text-center text-warning"> Nenhuma Prestação de Contas adicionada</h2>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

institucional/templates/institucional_historico.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static "css/historico.css" %}"/>


<div class="container padding">
    <div class="jumbotron">
        <h1 class="text-center">Histórico CADir UnB</h1>
        <p class="text-center my-5">Manter uma memória institucional é sempre importante. Confira abaixo as gestões que já administraram o CADir!</p>
        <div class="timeline">
            {% for logo in logos%}
                <div class="container-tl {%if forloop.counter0|divisibleby:2 %} left {% else %} right {% endif %}">
                    <div class="content-tl">
                        <h2 class="text-center"> {{ logo.nome }}</h2>
                        <h3 class="text-center"><span class="small text-gray"><i class="far fa-calendar-alt"></i>  {{logo.ano_inicial}} - {{logo.ano_final}} </span><h3>
                        <img class="img-fluid" src="../../media/{{logo.logo}}" alt="">
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="padding">
            <h1 class="text-center"> Mais sobre o histórico</h1>
            {{ historico.texto|safe }}
        </div>
    </div>
</div>


{% endblock %}

institucional/templates/institucional_index.html
{% extends 'base.html' %}

{% load tz %}
{% load static %}
{% block content %}
    <div class="container padding">
        <div class="jumbotron">
            <h1 class="text-center">Institucional</h1>

            <div class="py-3">
                <h2> O que é um centro acadêmico ?</h2>
                <p> O Centro Acadêmico exerce o papel de uma associação estudantil que integra os estudantes de seu
                    respectivo curso por meio de conselhos e assembleias, levando as pautas destes para a sociedade
                    civil, amplificando a voz do corpo estudantil e enriquecendo os debates. Esse direito é
                    regulamentado pela Lei Federal nº 7.395 de 31 de outubro de 1985.</p>

                <p>Discussões são realizadas nas assembleias estudantis e nos conselhos, tanto no âmbito das
                    universidades como em outras instituições. Desse modo, o CA procura encontrar soluções para as
                    problemáticas que afligem os estudantes, com o objetivo de melhorar o espaço de aprendizado do corpo
                    discente e estabelecer um diálogo entre aqueles que formam a Faculdade de Direito como um todo.</p>

                <p>No caso do CADir, diversas gestões escreveram suas histórias e o papel destas até hoje pode ser
                    estudado para revelar um aspecto histórico do corpo estudantil.</p>
            </div>

            <div class="py-3">
                <h2>Postagens Recentes</h2>
                {% if Postagens %}
                    <div class="list-group">
                        {% for postagem in Postagens %}
                            <a href="{% url 'institucional:postagem_show' pk=postagem.nome %}"
                               class="list-group-item list-group-item-action flex-column align-items-start">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">{{ postagem.nome }}</h5>
                                    <small>{{ postagem.created_at|timesince:Hoje }} </small>
                                </div>
                                <p class="mb-1"> {{ postagem.desc }}</p>
                            </a>
                        {% endfor %}
                    </div>
                {% else %}
                    <h3 class="text-center text-warning"> Ainda não há postagens disponíveis</h3>
                {% endif %}
                <div class="text-center ver-mais">
                    <a class="btn btn-primary" href="{% url 'institucional:postagens_index' %}">Ver todas as
                        postagens</a>
                </div>
            </div>


            <div class="py-3">
                <h2> Prestação de contas </h2>
                <p> Tendo em mente a relevância do papel do CADir de representar os estudantes da Faculdade de Direito e
                    a
                    confiança na gestão eleita, faz-se expresso o dever de prestação de contas e de manutenção da
                    transparência.</p>

                <div class="text-center ver-mais">
                    <a class="btn btn-primary" href="{% url 'institucional:institucional_contas' %}">Ver
                        Prestações de Contas</a>
                </div>
            </div>

            <div class="py-3">
                <h2> Histórico do CADir</h2>
                <p> O Centro Acadêmico de Direito da Universidade de Direito é uma instituição de décadas de história e
                    eventos marcantes. Diversas gestões marcaram seu passado e fizeram dele o que é hoje. </p>
                <div class="text-center ver-mais">
                    <a class="btn btn-primary" href="{% url 'institucional:institucional_historico' %}"> Histórico
                        Completo</a>
                </div>
            </div>

            <div class="py-3">
                <h2> Atas </h2>
                <p> Aqui é possível acessar as atas das reuniões do conselho. Uma maneira mais fácil de saber o que está
                    acontecendo nas reuniões</p>
                <div class="text-center ver-mais">
                    <a class="btn btn-primary" href="{% url 'institucional:institucional_atas' %}"> Ver atas</a>
                </div>
            </div>

            <div class="py-3">
                <h2> Estatuto </h2>
                <br>
                <div class="list-group">
                    {% if Estatutos %}
                        {% for estatuto in Estatutos %}
                            <a href="{% get_media_prefix %}{{ estatuto.file }}" target="_blank"
                               class="list-group-item list-group-item-action">
                                <span class="text-primary"> {{ estatuto.nome }} </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <h4 class="text-warning"> Ainda não foi adicionado algum Estatuto</h4>
                    {% endif %}
                </div>
            </div>

        </div>
    </div>
{% endblock %}

institucional/templates/postagem_show.html
{% extends 'base.html' %}

{% block content %}
    <div class="container padding">
        <div class="jumbotron">
            <h1 class="text-center">{{ Postagem.nome }}</h1>
            <div class="text-center padding">
                {{ Postagem.text|safe }}
            </div>

            <small> Criado há: {{ Postagem.created_at|timesince:Hoje }} </small><br>
            <small> Atualizado há: {{ Postagem.updated_at|timesince:Hoje }} </small>
        </div>
    </div>
{% endblock %}

institucional/templates/postagens_index.html
{% extends 'base.html' %}

{% load tz %}
{% block content %}
    <div class="container padding">
        <div class="jumbotron">
            <h1 class="text-center">Todas as postagens</h1>
            {% if not Postagens %}
                <h2 class="text-center text-warning"> Ainda não há postagens disponíveis </h2>
            {% endif %}
            <div class="list-group">
                {% for postagem in Postagens %}
                    <a href="{% url 'institucional:postagem_show' pk=postagem.nome %}"
                       class="list-group-item list-group-item-action flex-column align-items-start">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{ postagem.nome }}</h5>
                            <small>{{ postagem.created_at|timesince:Hoje }} </small>
                        </div>
                        <p class="mb-1"> {{ postagem.desc }}</p>
                    </a>
                {% endfor %}
            </div>

            <div class="pagination padding text-center">
                <span class="step-links">
                    {% if Postagens.has_previous %}
                        <a class="btn btn-info" href="?page=1">&laquo; Primeira </a>
                        <a class="btn btn-info" href="?page={{ Postagens.previous_page_number }}"> Anterior</a>
                    {% endif %}

                    <span class="current">
                        Page {{ Postagens.number }} of {{ Postagens.paginator.num_pages }}.
                    </span>

                    {% if Postagens.has_next %}
                        <a class="btn btn-info" href="?page={{ Postagens.next_page_number }}">Próxima</a>
                        <a class="btn btn-info" href="?page={{ Postagens.paginator.num_pages }}">Última &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
{% endblock %}